version: "3.2"

services:
    hub:
        image: "selenium/hub:3.7.1"
        ports:
            - 4444:4444
    node-firefox:
        image: "selenium/node-firefox:3.7.1"
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
    node-chrome:
        image: "selenium/node-chrome:3.7.1"
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
